// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtZ75nBdEe_jzl8Bbb7bPe5oCGgAYnWU',
    appId: '1:927418069292:web:c32bd3dddf41ab8e7dbc89',
    messagingSenderId: '927418069292',
    projectId: 'flutter-project-23fcc',
    authDomain: 'flutter-project-23fcc.firebaseapp.com',
    storageBucket: 'flutter-project-23fcc.appspot.com',
    measurementId: 'G-2JXWTLH5DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUrY0X4yVW8CzFZk6lbifiloGTRPu4tqY',
    appId: '1:927418069292:android:bb8cb1b503c306bb7dbc89',
    messagingSenderId: '927418069292',
    projectId: 'flutter-project-23fcc',
    storageBucket: 'flutter-project-23fcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5vQ5vWi2vu4x-I6Ve8tVEMR2GrjcpKQc',
    appId: '1:927418069292:ios:d20073469d49b1e87dbc89',
    messagingSenderId: '927418069292',
    projectId: 'flutter-project-23fcc',
    storageBucket: 'flutter-project-23fcc.appspot.com',
    iosBundleId: 'com.example.billSplitterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5vQ5vWi2vu4x-I6Ve8tVEMR2GrjcpKQc',
    appId: '1:927418069292:ios:d20073469d49b1e87dbc89',
    messagingSenderId: '927418069292',
    projectId: 'flutter-project-23fcc',
    storageBucket: 'flutter-project-23fcc.appspot.com',
    iosBundleId: 'com.example.billSplitterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTtZ75nBdEe_jzl8Bbb7bPe5oCGgAYnWU',
    appId: '1:927418069292:web:0937f2fe9874854a7dbc89',
    messagingSenderId: '927418069292',
    projectId: 'flutter-project-23fcc',
    authDomain: 'flutter-project-23fcc.firebaseapp.com',
    storageBucket: 'flutter-project-23fcc.appspot.com',
    measurementId: 'G-4JHPF0XB0Q',
  );

}